// AUTO-GENERATED by scripts/build_case_study.py
// Do not edit by hand. Re-run the script after changing the source docx.

export type Block =
  | { kind: "page"; number: number }
  | { kind: "heading"; level: number; text: string }
  | { kind: "para"; text: string }
  | { kind: "list"; items: string[]; ordered?: boolean }
  | { kind: "code"; code: string; language?: string; filename?: string }
  | {
      kind: "image";
      src: string;
      alt: string;
      width: number;
      height: number;
      caption?: string;
    }
  | { kind: "table"; rows: string[][] }
  | {
      kind: "card";
      title: string;
      body: string;
    };

export type Part = {
  n: number;
  title: string;
  blocks: Block[];
};

export type CaseStudy = {
  slug: string;
  meta: {
    publishedAt: string;
    updatedAt: string;
    status: "draft" | "demo" | "live";
    readingMinutes: number;
  };
  seo: Record<string, unknown>;
  hero: Record<string, unknown>;
  challenge: Record<string, unknown>;
  gaps: Record<string, unknown>;
  solution: Record<string, unknown>;
  testLab: Record<string, unknown>;
  timeline: Record<string, unknown>;
  stack: Record<string, unknown>;
  results: Record<string, unknown>;
  faq: Record<string, unknown>;
  cta: Record<string, unknown>;
  parts: Part[];
};

export const caseStudy: CaseStudy = {
  slug: "clickmasters-case-study-saas-booking-platform-qa",
  meta: {
    publishedAt: "2026-10-05",
    updatedAt: "2026-10-05",
    status: "demo",
    readingMinutes: 14,
  },
  seo: {
    url: "https://clickmasterssoftwaredevelopmentcompany.com/case-studies/pre-launch-qa-saas-booking-platform",
    canonical:
      "https://clickmasterssoftwaredevelopmentcompany.com/case-studies/pre-launch-qa-saas-booking-platform",
    title:
      "Pre-launch QA for a SaaS Booking Platform | Clickmasters Case Study",
    description:
      "How Clickmasters plans and runs pre-launch QA for a multi-tenant SaaS booking platform: risk-based manual testing, double-booking checks, Mollie deposit status mapping and tenant-separation checks.",
    h1: "Pre-launch QA for a SaaS Booking Platform: Finding the Failures That Matter",
    robots: "index, follow",
    og: {
      type: "article",
      title:
        "Pre-launch QA for a SaaS booking platform: finding the failures that matter",
      description:
        "A risk-based manual QA plan for a multi-tenant booking platform: double bookings, Mollie deposit statuses and tenant separation, tested before the first real business signs up.",
      imageWidth: 1200,
      imageHeight: 630,
    },
    twitter: {
      card: "summary_large_image",
    },
    keywords: [
      {
        term: "pre-launch qa saas booking platform",
        volume: 210,
        difficulty: 34,
        role: "Primary",
      },
      {
        term: "software testing and qa",
        volume: 5400,
        difficulty: 48,
        role: "Head term",
      },
      {
        term: "saas qa testing",
        volume: 720,
        difficulty: 39,
        role: "Secondary",
      },
      {
        term: "booking system testing",
        volume: 320,
        difficulty: 28,
        role: "Secondary",
      },
      {
        term: "multi-tenant saas testing",
        volume: 170,
        difficulty: 31,
        role: "Secondary",
      },
      {
        term: "tenant separation testing",
        volume: 90,
        difficulty: 22,
        role: "Long tail",
      },
      {
        term: "double booking prevention testing",
        volume: 70,
        difficulty: 25,
        role: "Long tail",
      },
      {
        term: "mollie payment testing",
        volume: 110,
        difficulty: 27,
        role: "Long tail",
      },
      {
        term: "release readiness review",
        volume: 260,
        difficulty: 33,
        role: "Secondary",
      },
    ],
    internalLinks: [
      {
        anchor: "Software testing and QA",
        href: "/services/software-testing-qa",
      },
      {
        anchor: "SaaS development",
        href: "/services/saas-development",
      },
      {
        anchor: "API integration",
        href: "/services/api-integration",
      },
      {
        anchor: "QA and DevOps",
        href: "/services/qa-devops",
      },
      {
        anchor: "Pre-launch QA for booking platforms",
        href: "/solutions/pre-launch-qa/booking-platforms",
      },
      {
        anchor: "Release-readiness review",
        href: "/solutions/release-readiness-review",
      },
      {
        anchor: "free QA scoping call",
        href: "/free-qa-scoping-call",
      },
      {
        anchor: "Contact Clickmasters",
        href: "/contact",
      },
    ],
  },
  hero: {
    eyebrow: "SOLUTION CASE STUDY · SOFTWARE TESTING AND QA",
    h1: "Pre-launch QA for a SaaS booking platform",
    subtitle:
      "Finding the failures that matter before the first real business signs up",
    byline:
      "Clickmasters · Clickmasterssoftwaredevelopmentcompany.com · October 2026",
    intro:
      "About this case study. It shows how Clickmasters plans and runs pre-launch QA for a SaaS booking platform, built from a founder's project brief: our method, test design, delivery plan and deliverables. Effort figures are estimates and outcomes are targets; it does not report results from a completed engagement.",
    title: "Summary",
    atAGlanceTitle: "At a glance",
    atAGlance: [
      {
        label: "Platform",
        value:
          "Multi-tenant SaaS for appointment booking, with a public booking link for each business",
      },
      {
        label: "Users covered",
        value:
          "Business owners and their customers; Super Admin where access is provided",
      },
      {
        label: "Payments",
        value: "Customer deposits through Mollie, tested in Mollie's test mode",
      },
      {
        label: "Plans",
        value: "Three subscription tiers with a free trial",
      },
      {
        label: "Devices",
        value: "Desktop, mobile and tablet; Chrome and Safari; installable PWA",
      },
      {
        label: "Engagement type",
        value: "Pre-launch manual QA and release-readiness review",
      },
      {
        label: "Estimated effort",
        value: "16 to 22 hours launch-critical; 32 to 46 hours full coverage",
      },
      {
        label: "Outputs",
        value:
          "Defect log, UX list, tenant-separation check sheet, release summary, retest report",
      },
    ],
    primaryCta: {
      label: "Book a free QA scoping call",
      href: "/free-qa-scoping-call",
    },
    secondaryCta: {
      label: "Contact Clickmasters",
      href: "/contact",
    },
  },
  challenge: {
    h2: "The challenge: every user journey, both roles, before the first real business signs up",
    lead: "A founder preparing to open a multi-tenant SaaS booking platform to its first real businesses needed an independent pass over every user journey: business owner and customer, desktop and mobile, deposits through Mollie and three subscription tiers.",
    research:
      "The product was live and in its final testing phase. Before inviting real businesses, the founder wanted an independent tester to use it end to end in both roles, as a shop owner and as a customer.",
    h3WhyHard: {
      h3: "Why booking platforms fail quietly",
      bullets: [
        {
          title: "Double booking.",
          body: "Two customers arrive for one appointment. Nothing errors; both bookings look valid.",
        },
        {
          title: "Payment and booking out of step.",
          body: "A deposit is paid but the booking never confirms, or a slot stays blocked after the customer abandons checkout. Mollie documents seven payment statuses, and an unpaid payment expires only after a method-specific window: 15 minutes for iDEAL, 30 minutes for cards.",
        },
        {
          title: "Cross-tenant data access.",
          body: "One business opens another's customer or booking by changing a link. In normal use each business only sees its own screens. OWASP ranks broken access control first in its Top 10:2025.",
        },
        {
          title: "Device-specific faults.",
          body: "The app will not install, or a form is unusable on one phone. On iOS a web app installs only from the Share menu, with no install prompt (MDN), so desktop testing alone misses it.",
        },
      ],
      closing:
        "A crash gets noticed on day one. The costly launch defects in a booking product are quieter, and they surface only when real customers arrive.",
    },
  },
  gaps: {
    h2: "What the brief asked for",
    intro:
      "The brief was specific about what good output looks like, and it also set a boundary. No penetration test was wanted, but obvious permission and data-isolation problems found during normal use had to be reported: one business must never reach another's customers, bookings or data.",
    rows: [
      {
        gap: "Every issue with a clear title",
        why: "The developer must be able to reproduce it",
        added:
          "Title, severity from Critical to Low, steps to reproduce, expected and actual results, the device and browser, and a screenshot or recording",
      },
      {
        gap: "Bugs kept apart from UX",
        why: "Improvement suggestions must not block a launch",
        added:
          "A separate list of UX and improvement suggestions, kept apart from the defect log",
      },
      {
        gap: "A short verdict",
        why: "The founder needs a clear decision before real businesses start",
        added:
          "A fix-first or go verdict on whether anything critical must be fixed before launch",
      },
      {
        gap: "One retest",
        why: "Every fix has to be confirmed, not assumed",
        added:
          "A retest after the developer's fixes, covering every fix plus a smoke re-run of the core journeys",
      },
      {
        gap: "Data isolation boundary",
        why: "One business must never reach another's customers, bookings or data",
        added:
          "Tenant-separation checks through normal use, with any exposure reported to the founder privately the same working day",
      },
    ],
  },
  solution: {
    h2: "Our approach: we test risk first",
    steps: [
      {
        n: 1,
        title: "Bookings without conflicts.",
        body: "We compare the slots offered with the configured opening hours and staff availability, submit the same slot from two devices within seconds, mix manual and online bookings, and check which slots reschedules and cancellations free up. Edge cases include midnight, same-day past slots and the repeated hour when clocks go back in October.",
      },
      {
        n: 2,
        title: "Deposits and statuses in step.",
        body: "Mollie's test mode lets a tester choose the outcome of each payment without moving money (Mollie: Testing). For paid, failed, cancelled and expired we check the booking status, whether the slot is held or released, and which emails go out. After each session we reconcile three counts: bookings created, payments shown and emails received.",
      },
      {
        n: 3,
        title: "Tenant separation.",
        body: "We set up two test businesses. Logged in as one, we try to open the other's customers, bookings, services and staff through ordinary links and by changing record identifiers in the address bar. Any exposure goes to the founder privately the same working day.",
      },
    ],
    rules: {
      h3: "Around that core",
      intro:
        "The first hours go to the three capabilities a launch cannot survive without, and everything else is covered around them.",
      bullets: [
        "Sign-up, email verification, password reset, onboarding and trial",
        "Plan limits and every transactional email",
        "Responsive layout and the installable app",
      ],
    },
  },
  testLab: {
    h3: "The booking and deposit flow under test",
    intro:
      "Figure 1. Booking and deposit flow: 3 steps, 4 payment outcomes. The paid path is checked by TEST-008. The three unpaid endings are checked by TEST-009, where a held slot that never frees is the main risk.",
  },
  timeline: {
    h3: "Payment status mapping",
    note: "The first column is Mollie's published list of statuses. The expected states are agreed with the founder before testing starts, because the founder's intended behaviour is the reference.",
    rows: [
      {
        time: "paid",
        channel: "Confirmed",
        what: "Held · Reachable in test mode: Yes",
      },
      {
        time: "open, customer left checkout",
        channel: "Awaiting payment",
        what: "Held until expiry, then released · Reachable in test mode: Yes",
      },
      {
        time: "canceled",
        channel: "Not confirmed",
        what: "Released, or held if retry is offered · Reachable in test mode: Yes",
      },
      {
        time: "failed",
        channel: "Not confirmed",
        what: "Released, or held if retry is offered · Reachable in test mode: Yes",
      },
      {
        time: "expired",
        channel: "Cancelled",
        what: "Released · Reachable in test mode: Yes, by selection on the test screen",
      },
      {
        time: "pending, authorized",
        channel: "Depends on the payment methods enabled",
        what: "To confirm · Reachable in test mode: Only if those methods are enabled",
      },
    ],
  },
  stack: {
    h2: "What we test: coverage map",
    intro:
      "The coverage map sets the priority for each area. Booking engine, payments and subscriptions, and tenant separation are Critical.",
    rows: [
      {
        layer: "Account and onboarding",
        what: "Sign-up, email verification, login and logout, password reset, onboarding to a bookable state, trial",
        why: "High",
      },
      {
        layer: "Business setup",
        what: "Services, staff, opening hours, staff availability, customer records, booking rules, deposit settings",
        why: "High",
      },
      {
        layer: "Booking engine",
        what: "Public booking link, slot generation, manual bookings, reschedule, cancel, completed and no-show, double-booking prevention",
        why: "Critical",
      },
      {
        layer: "Payments and subscriptions",
        what: "Deposit journey for each payment outcome, status sync, plan limits, upgrades and downgrades, trial end",
        why: "Critical",
      },
      {
        layer: "Emails",
        what: "Confirmations, reschedules, cancellations, reminders and account emails: recipient, content, links, timing, duplicates",
        why: "High",
      },
      {
        layer: "Devices and PWA",
        what: "Desktop, mobile and tablet in Chrome and Safari; install and relaunch of the PWA",
        why: "Medium",
      },
      {
        layer: "Tenant separation",
        what: "Cross-business access to customers, bookings, services and staff; plan-gated pages by direct URL",
        why: "Critical",
      },
      {
        layer: "Admin and Super Admin",
        what: "Agreed admin functions, where access is provided",
        why: "Agreed at kickoff",
      },
    ],
  },
  results: {
    h2: "Test design: twenty test charters",
    intro:
      "Twenty test charters cover the brief. Each traces to a line in the brief and is executed manually; TEST-008, TEST-009 and TEST-011 are the strongest candidates for later automation.",
    note: "The severity scale is agreed at kickoff so priorities are never disputed later.",
    rows: [
      {
        n: 1,
        measure: "TEST-001 Sign-up, verification, login, logout",
        how: "Valid sign-up; duplicate email; unverified login; logout then back",
        target:
          "Account usable only after verification; session ends on logout",
      },
      {
        n: 2,
        measure: "TEST-002 Forgot and reset password",
        how: "Reset by link; reuse the link; old password; unknown email",
        target: "Only the newest link works, once",
      },
      {
        n: 3,
        measure: "TEST-003 Onboarding and trial",
        how: "Complete; abandon and resume; trial banner and dates",
        target:
          "Business reaches a bookable state; trial matches the intended rule",
      },
      {
        n: 4,
        measure: "TEST-004 Services and staff",
        how: "Required fields; zero and very long durations; zero and decimal prices; edit or delete with future bookings",
        target:
          "Valid data saved and shown publicly; invalid data rejected with a message",
      },
      {
        n: 5,
        measure: "TEST-005 Hours and availability to slots",
        how: "Opening versus staff hours; closed day; last slot before closing; service longer than the time left",
        target: "Offered slots equal the configured window",
      },
      {
        n: 6,
        measure: "TEST-006 Customer management",
        how: "Create, search, edit; duplicate email or phone; customer created by a booking",
        target: "Records correct; duplicates follow the intended rule",
      },
      {
        n: 7,
        measure: "TEST-007 Booking rules and deposits",
        how: "Lead time; furthest advance date; cancellation cut-off; fixed and percentage deposit; rounding",
        target: "Each rule holds at its boundary",
      },
      {
        n: 8,
        measure: "TEST-008 Public booking with deposit, happy path",
        how: "Book on each primary device; choose paid; return to the site",
        target: "Confirmed booking, paid status, slot removed, emails sent",
      },
      {
        n: 9,
        measure: "TEST-009 Payment not completed",
        how: "Failed; cancelled; expired; tab closed at checkout; retry; double click on pay",
        target:
          "Agreed status mapping holds; no paid payment without a booking",
      },
      {
        n: 10,
        measure: "TEST-010 Manual booking, reschedule, cancel, outcomes",
        how: "Manual booking; reschedule and cancel by both roles; completed; no-show; status changed twice",
        target: "Status, calendar and slot agree after each action",
      },
      {
        n: 11,
        measure: "TEST-011 Double booking and concurrency",
        how: "Two devices submit one slot; manual versus online; two tabs; overlapping services for one staff member",
        target: "Exactly one confirmed booking per staff member and time",
      },
      {
        n: 12,
        measure: "TEST-012 Availability edge cases",
        how: "Midnight; today's past slots; the repeated hour in October; day off added after a booking",
        target: "No slot outside availability; times display consistently",
      },
      {
        n: 13,
        measure: "TEST-013 Subscription, trial and plan limits",
        how: "Limits per tier; upgrade; downgrade; gated feature by URL; trial end if it can be triggered",
        target: "Features match the plan; blocked items say why",
      },
      {
        n: 14,
        measure: "TEST-014 Email matrix",
        how: "Each trigger; recipient; content; links; time shown; duplicates; reminder timing",
        target: "One correct email per trigger",
      },
      {
        n: 15,
        measure: "TEST-015 Responsive and cross-browser sweep",
        how: "Critical screens per device; rotation; long names; keyboard over forms; date and time pickers",
        target: "No broken layout or unusable control",
      },
      {
        n: 16,
        measure: "TEST-016 PWA install and use",
        how: "Install on Android Chrome and iOS Safari; icon and name; relaunch stays logged in; return from checkout",
        target: "Installs and runs, or the gap is documented",
      },
      {
        n: 17,
        measure: "TEST-017 Tenant separation",
        how: "The tenant-separation checks across customers, bookings, services and staff",
        target: "No cross-tenant read or write",
      },
      {
        n: 18,
        measure: "TEST-018 Admin and Super Admin",
        how: "Functions agreed with the founder",
        target: "As agreed",
      },
      {
        n: 19,
        measure: "TEST-019 Retest and smoke regression",
        how: "Re-run the steps of each fixed defect; re-run sign-up, booking and reschedule",
        target: "Each fix Verified or Reopened; smoke passes",
      },
      {
        n: 20,
        measure: "TEST-020 Report quality review",
        how: "Mandatory fields on every record; bugs and UX notes on separate lists; summary traces to the log",
        target: "100% complete",
      },
    ],
  },
  faq: {
    h2: "Frequently asked questions",
    items: [
      {
        q: "What is pre-launch QA for a SaaS booking platform?",
        a: "It is a risk-based manual test run before real businesses sign up. It covers every user journey in both roles, business owner and customer, on desktop and mobile, across deposits through Mollie and three subscription tiers. It starts where a launch failure would hurt most: double bookings, payment and booking statuses drifting apart, and one business seeing another's data.",
      },
      {
        q: "Why do booking platforms fail quietly?",
        a: "A crash gets noticed on day one. The costly launch defects in a booking product are quieter. Double bookings do not error; both bookings look valid. A deposit can be paid while the booking never confirms, or a slot stays blocked after a customer abandons checkout. Cross-tenant data access is invisible in normal use because each business only sees its own screens.",
      },
      {
        q: "How do you test double bookings?",
        a: "We submit the same slot from two devices within seconds, mix manual and online bookings, open two tabs, and test overlapping services for one staff member. The pass condition is exactly one confirmed booking per staff member and time. Edge cases include midnight, same-day past slots and the repeated hour when clocks go back in October.",
      },
      {
        q: "How do you test deposits through Mollie?",
        a: "Mollie's test mode lets a tester choose the outcome of each payment without moving money. For paid, failed, cancelled and expired we check the booking status, whether the slot is held or released, and which emails go out. After each session we reconcile three counts: bookings created, payments shown and emails received. An unpaid payment expires only after a method-specific window: 15 minutes for iDEAL, 30 minutes for cards.",
      },
      {
        q: "What is tenant separation testing?",
        a: "We set up two test businesses. Logged in as one, we try to open the other's customers, bookings, services and staff through ordinary links and by changing record identifiers in the address bar. Any exposure goes to the founder privately the same working day. These checks use no scanners, scripts or attack payloads, and they are not a penetration test.",
      },
      {
        q: "How do you document a bug?",
        a: "Every issue gets a clear title, a severity from Critical to Low, steps to reproduce, expected and actual results, the device and browser with exact versions, and a screenshot or recording. Bugs are kept apart from UX and improvement suggestions. One issue per record so the developer can reproduce and fix without follow-up questions.",
      },
      {
        q: "What severity scale do you use?",
        a: "Critical blocks a core journey for all users, loses or exposes data, or takes money wrongly. High is a core function that fails for some users or works only with a costly workaround. Medium is a secondary function that fails, or a core one that misbehaves with an easy workaround. Low is cosmetic or wording with no functional effect. The scale is agreed at kickoff so priorities are never disputed later.",
      },
      {
        q: "What does the founder receive at the end?",
        a: "A defect log with every field the brief asked for, a separate list of UX and improvement suggestions, a tenant-separation check sheet, an evidence pack named by defect ID, a one-page release summary with the fix-first or go verdict, a list of what was not tested and why, and a retest report covering every fix plus a smoke re-run of the core journeys.",
      },
      {
        q: "What is not covered in this engagement?",
        a: "Load and performance testing, penetration testing, accessibility conformance audits and legal or regulatory compliance reviews sit outside this scope, and live-mode payments are not exercised. The release summary says so plainly. Where they matter, we recommend them as follow-on work.",
      },
      {
        q: "How long does pre-launch QA take?",
        a: "The launch-critical option is an estimated 16 to 22 hours and covers the three priority areas end to end, sign-up and onboarding, the core emails, one plan tier in depth with spot checks on the others, and desktop Chrome, iPhone Safari and Android Chrome, with the retest included. The full coverage option is an estimated 32 to 46 hours and adds every rule and status, all payment methods offered, every plan tier, reminders, the complete device matrix and the installed PWA.",
      },
    ],
  },
  cta: {
    h2: "Preparing to onboard your first customers?",
    body: "Contact Clickmasters with a short description of your platform. We will reply with scoping questions and a written estimate for both scope options. The launch-critical option covers the three priority areas end to end; the full coverage option adds every rule, status, plan tier and device.",
    primary: {
      label: "Book a free QA scoping call",
      href: "/free-qa-scoping-call",
    },
    secondary: {
      label: "Contact Clickmasters",
      href: "/contact",
    },
    related:
      "Software testing and QA · SaaS development · API integration · QA and DevOps",
  },
  parts: [
    {
      n: 0,
      title: "Summary",
      blocks: [
        {
          kind: "para",
          text: "A founder preparing to open a multi-tenant SaaS booking platform to its first real businesses needed an independent pass over every user journey: business owner and customer, desktop and mobile, deposits through Mollie and three subscription tiers.",
        },
        {
          kind: "para",
          text: "This case study sets out how Clickmasters plans and runs that work. It is a risk-based manual test that starts where a launch failure would hurt most: double bookings, payment and booking statuses drifting apart, and one business seeing another's data. It ends with a reproducible defect log, a clear fix-first or go verdict, and a retest of every fix.",
        },
      ],
    },
    {
      n: 1,
      title: "The challenge",
      blocks: [
        {
          kind: "para",
          text: "The founder had built a multi-tenant booking platform. Each business signs up, sets its services, staff and opening hours, and shares a public booking link. Customers choose a slot and pay a deposit through Mollie. Businesses move from a free trial to one of three plan tiers, and the app can be installed on a phone as a PWA.",
        },
        {
          kind: "para",
          text: "The product was live and in its final testing phase. Before inviting real businesses, the founder wanted an independent tester to use it end to end in both roles, as a shop owner and as a customer.",
        },
        {
          kind: "para",
          text: "The brief was specific about what good output looks like:",
        },
        {
          kind: "list",
          items: [
            "Every issue with a clear title, a severity from Critical to Low, steps to reproduce, expected and actual results, the device and browser, and a screenshot or recording.",
            "Bugs kept apart from UX and improvement suggestions.",
            "A short verdict on whether anything critical must be fixed before real businesses start.",
            "One retest after the developer's fixes.",
          ],
          ordered: true,
        },
        {
          kind: "para",
          text: "It also set a boundary. No penetration test was wanted, but obvious permission and data-isolation problems found during normal use had to be reported: one business must never reach another's customers, bookings or data.",
        },
      ],
    },
    {
      n: 2,
      title: "Why booking platforms fail quietly",
      blocks: [
        {
          kind: "para",
          text: "A crash gets noticed on day one. The costly launch defects in a booking product are quieter, and they surface only when real customers arrive.",
        },
        {
          kind: "table",
          rows: [
            ["Failure", "How it shows up", "Why it is easy to miss"],
            [
              "Double booking",
              "Two customers arrive for one appointment",
              "Nothing errors; both bookings look valid",
            ],
            [
              "Payment and booking out of step",
              "A deposit is paid but the booking never confirms, or a slot stays blocked after the customer abandons checkout",
              "Mollie documents seven payment statuses, and an unpaid payment expires only after a method-specific window: 15 minutes for iDEAL, 30 minutes for cards",
            ],
            [
              "Cross-tenant data access",
              "One business opens another's customer or booking by changing a link",
              "In normal use each business only sees its own screens. OWASP ranks broken access control first in its Top 10:2025.",
            ],
            [
              "Device-specific faults",
              "The app will not install, or a form is unusable on one phone",
              "On iOS a web app installs only from the Share menu, with no install prompt (MDN), so desktop testing alone misses it",
            ],
          ],
        },
      ],
    },
    {
      n: 3,
      title: "Our approach",
      blocks: [
        {
          kind: "para",
          text: "We test risk first. The first hours go to the three capabilities a launch cannot survive without, and everything else is covered around them.",
        },
        {
          kind: "card",
          title: "Bookings without conflicts",
          body: "We compare the slots offered with the configured opening hours and staff availability, submit the same slot from two devices within seconds, mix manual and online bookings, and check which slots reschedules and cancellations free up. Edge cases include midnight, same-day past slots and the repeated hour when clocks go back in October.",
        },
        {
          kind: "card",
          title: "Deposits and statuses in step",
          body: "Mollie's test mode lets a tester choose the outcome of each payment without moving money (Mollie: Testing). For paid, failed, cancelled and expired we check the booking status, whether the slot is held or released, and which emails go out. After each session we reconcile three counts: bookings created, payments shown and emails received.",
        },
        {
          kind: "card",
          title: "Tenant separation",
          body: "We set up two test businesses. Logged in as one, we try to open the other's customers, bookings, services and staff through ordinary links and by changing record identifiers in the address bar. Any exposure goes to the founder privately the same working day.",
        },
        {
          kind: "para",
          text: "Around that core we cover sign-up, email verification, password reset, onboarding and trial, plan limits, every transactional email, responsive layout and the installable app.",
        },
        {
          kind: "heading",
          level: 2,
          text: "The booking and deposit flow under test",
        },
        {
          kind: "image",
          src: "/case-studies/approach.png",
          alt: "Booking and deposit flow: 3 steps, 4 payment outcomes",
          width: 1200,
          height: 675,
        },
        {
          kind: "para",
          text: "Figure 1. Booking and deposit flow: 3 steps, 4 payment outcomes",
        },
        {
          kind: "para",
          text: "The paid path is checked by TEST-008. The three unpaid endings are checked by TEST-009, where a held slot that never frees is the main risk.",
        },
      ],
    },
    {
      n: 4,
      title: "What we test",
      blocks: [
        {
          kind: "heading",
          level: 2,
          text: "Coverage map",
        },
        {
          kind: "table",
          rows: [
            ["Area", "What we check", "Priority"],
            [
              "Account and onboarding",
              "Sign-up, email verification, login and logout, password reset, onboarding to a bookable state, trial",
              "High",
            ],
            [
              "Business setup",
              "Services, staff, opening hours, staff availability, customer records, booking rules, deposit settings",
              "High",
            ],
            [
              "Booking engine",
              "Public booking link, slot generation, manual bookings, reschedule, cancel, completed and no-show, double-booking prevention",
              "Critical",
            ],
            [
              "Payments and subscriptions",
              "Deposit journey for each payment outcome, status sync, plan limits, upgrades and downgrades, trial end",
              "Critical",
            ],
            [
              "Emails",
              "Confirmations, reschedules, cancellations, reminders and account emails: recipient, content, links, timing, duplicates",
              "High",
            ],
            [
              "Devices and PWA",
              "Desktop, mobile and tablet in Chrome and Safari; install and relaunch of the PWA",
              "Medium",
            ],
            [
              "Tenant separation",
              "Cross-business access to customers, bookings, services and staff; plan-gated pages by direct URL",
              "Critical",
            ],
            [
              "Admin and Super Admin",
              "Agreed admin functions, where access is provided",
              "Agreed at kickoff",
            ],
          ],
        },
        {
          kind: "heading",
          level: 2,
          text: "Payment status mapping",
        },
        {
          kind: "para",
          text: "The first column is Mollie's published list of statuses. The expected states are agreed with the founder before testing starts, because the founder's intended behaviour is the reference.",
        },
        {
          kind: "table",
          rows: [
            [
              "Mollie status",
              "Expected booking state",
              "Expected slot",
              "Reachable in test mode",
            ],
            ["paid", "Confirmed", "Held", "Yes"],
            [
              "open, customer left checkout",
              "Awaiting payment",
              "Held until expiry, then released",
              "Yes",
            ],
            [
              "canceled",
              "Not confirmed",
              "Released, or held if retry is offered",
              "Yes",
            ],
            [
              "failed",
              "Not confirmed",
              "Released, or held if retry is offered",
              "Yes",
            ],
            [
              "expired",
              "Cancelled",
              "Released",
              "Yes, by selection on the test screen",
            ],
            [
              "pending, authorized",
              "Depends on the payment methods enabled",
              "To confirm",
              "Only if those methods are enabled",
            ],
          ],
        },
        {
          kind: "heading",
          level: 2,
          text: "Tenant-separation checks",
        },
        {
          kind: "para",
          text: "These checks use no scanners, scripts or attack payloads. They find obvious isolation faults through normal use and are not a penetration test.",
        },
        {
          kind: "table",
          rows: [
            ["Check", "How", "Pass condition"],
            [
              "Cross-business records",
              "Logged in as business B, open business A's record links and change record identifiers for customers, bookings, services and staff",
              "Access denied and nothing shown",
            ],
            [
              "Public booking links",
              "Change the booking reference in a customer's booking-management link",
              "Only the customer's own booking is shown",
            ],
            [
              "Session and reset handling",
              "Log out then press back; reuse a reset link; use an old link after a password change",
              "Session ended; link rejected",
            ],
            [
              "Plan-gated features",
              "Open higher-plan features by direct URL on a lower plan; exceed a plan limit",
              "Blocked with a clear message",
            ],
          ],
        },
      ],
    },
    {
      n: 5,
      title: "Test design",
      blocks: [
        {
          kind: "para",
          text: "Twenty test charters cover the brief. Each traces to a line in the brief and is executed manually; TEST-008, TEST-009 and TEST-011 are the strongest candidates for later automation.",
        },
        {
          kind: "heading",
          level: 2,
          text: "Test charters",
        },
        {
          kind: "table",
          rows: [
            [
              "ID",
              "Charter",
              "Key checks, including negative and boundary cases",
              "Expected outcome",
            ],
            [
              "TEST-001",
              "Sign-up, verification, login, logout",
              "Valid sign-up; duplicate email; unverified login; logout then back",
              "Account usable only after verification; session ends on logout",
            ],
            [
              "TEST-002",
              "Forgot and reset password",
              "Reset by link; reuse the link; old password; unknown email",
              "Only the newest link works, once",
            ],
            [
              "TEST-003",
              "Onboarding and trial",
              "Complete; abandon and resume; trial banner and dates",
              "Business reaches a bookable state; trial matches the intended rule",
            ],
            [
              "TEST-004",
              "Services and staff",
              "Required fields; zero and very long durations; zero and decimal prices; edit or delete with future bookings",
              "Valid data saved and shown publicly; invalid data rejected with a message",
            ],
            [
              "TEST-005",
              "Hours and availability to slots",
              "Opening versus staff hours; closed day; last slot before closing; service longer than the time left",
              "Offered slots equal the configured window",
            ],
            [
              "TEST-006",
              "Customer management",
              "Create, search, edit; duplicate email or phone; customer created by a booking",
              "Records correct; duplicates follow the intended rule",
            ],
            [
              "TEST-007",
              "Booking rules and deposits",
              "Lead time; furthest advance date; cancellation cut-off; fixed and percentage deposit; rounding",
              "Each rule holds at its boundary",
            ],
            [
              "TEST-008",
              "Public booking with deposit, happy path",
              "Book on each primary device; choose paid; return to the site",
              "Confirmed booking, paid status, slot removed, emails sent",
            ],
            [
              "TEST-009",
              "Payment not completed",
              "Failed; cancelled; expired; tab closed at checkout; retry; double click on pay",
              "Agreed status mapping holds; no paid payment without a booking",
            ],
            [
              "TEST-010",
              "Manual booking, reschedule, cancel, outcomes",
              "Manual booking; reschedule and cancel by both roles; completed; no-show; status changed twice",
              "Status, calendar and slot agree after each action",
            ],
            [
              "TEST-011",
              "Double booking and concurrency",
              "Two devices submit one slot; manual versus online; two tabs; overlapping services for one staff member",
              "Exactly one confirmed booking per staff member and time",
            ],
            [
              "TEST-012",
              "Availability edge cases",
              "Midnight; today's past slots; the repeated hour in October; day off added after a booking",
              "No slot outside availability; times display consistently",
            ],
            [
              "TEST-013",
              "Subscription, trial and plan limits",
              "Limits per tier; upgrade; downgrade; gated feature by URL; trial end if it can be triggered",
              "Features match the plan; blocked items say why",
            ],
            [
              "TEST-014",
              "Email matrix",
              "Each trigger; recipient; content; links; time shown; duplicates; reminder timing",
              "One correct email per trigger",
            ],
            [
              "TEST-015",
              "Responsive and cross-browser sweep",
              "Critical screens per device; rotation; long names; keyboard over forms; date and time pickers",
              "No broken layout or unusable control",
            ],
            [
              "TEST-016",
              "PWA install and use",
              "Install on Android Chrome and iOS Safari; icon and name; relaunch stays logged in; return from checkout",
              "Installs and runs, or the gap is documented",
            ],
            [
              "TEST-017",
              "Tenant separation",
              "The tenant-separation checks in section 4 across customers, bookings, services and staff",
              "No cross-tenant read or write",
            ],
            [
              "TEST-018",
              "Admin and Super Admin",
              "Functions agreed with the founder",
              "As agreed",
            ],
            [
              "TEST-019",
              "Retest and smoke regression",
              "Re-run the steps of each fixed defect; re-run sign-up, booking and reschedule",
              "Each fix Verified or Reopened; smoke passes",
            ],
            [
              "TEST-020",
              "Report quality review",
              "Mandatory fields on every record; bugs and UX notes on separate lists; summary traces to the log",
              "100% complete",
            ],
          ],
        },
        {
          kind: "heading",
          level: 2,
          text: "Severity scale",
        },
        {
          kind: "para",
          text: "The scale is agreed at kickoff so priorities are never disputed later.",
        },
        {
          kind: "table",
          rows: [
            ["Severity", "Definition", "Illustration"],
            [
              "Critical",
              "Blocks a core journey for all users, loses or exposes data, or takes money wrongly",
              "Two customers confirmed in one slot",
            ],
            [
              "High",
              "A core function fails for some users, or works only with a costly workaround",
              "Confirmation email missing for bookings made in one browser",
            ],
            [
              "Medium",
              "A secondary function fails, or a core one misbehaves with an easy workaround",
              "Edited staff hours appear only after a reload",
            ],
            [
              "Low",
              "Cosmetic or wording issue with no functional effect",
              "Button misaligned on tablet",
            ],
          ],
        },
        {
          kind: "heading",
          level: 2,
          text: "Device and browser matrix",
        },
        {
          kind: "table",
          rows: [
            ["Device", "Browser", "Coverage"],
            [
              "Windows or macOS desktop",
              "Chrome, current stable",
              "Launch-critical and full",
            ],
            ["macOS desktop", "Safari, current", "Spot check, then full"],
            ["iPhone", "Safari", "Launch-critical and full"],
            ["Android phone", "Chrome", "Launch-critical and full"],
            [
              "iPad or Android tablet",
              "Safari or Chrome",
              "Spot check, then full",
            ],
            [
              "iPhone and Android phone",
              "Installed PWA, launched from the home screen",
              "Full coverage",
            ],
          ],
        },
        {
          kind: "para",
          text: "Exact OS and browser versions are recorded on every report.",
        },
        {
          kind: "heading",
          level: 2,
          text: "How we document a bug",
        },
        {
          kind: "para",
          text: "This is a format sample with synthetic data, not a finding.",
        },
        {
          kind: "list",
          items: [
            "Title: Booking: slot stays blocked after the deposit payment expires",
          ],
        },
        {
          kind: "list",
          items: ["Type and severity: Bug, High"],
        },
        {
          kind: "list",
          items: [
            "Device and browser: iPhone, Safari; exact versions recorded per session",
          ],
        },
        {
          kind: "heading",
          level: 3,
          text: "Steps to reproduce:",
        },
        {
          kind: "list",
          items: [
            "Open the public booking link of TEST Salon A.",
            "Choose service TEST Cut 30, staff TEST Staff 1, tomorrow at 10:00.",
            "Enter customer details and continue to payment.",
            "On the Mollie test screen choose Expired and continue.",
            "Reopen the booking link and look at tomorrow at 10:00.",
          ],
          ordered: true,
        },
        {
          kind: "list",
          items: [
            "Expected result: the booking shows as cancelled and 10:00 is offered again.",
            "Actual result: 10:00 is not offered; the dashboard shows the booking as awaiting payment.",
            "Evidence: screen recording and two screenshots; reproduced 3 of 3 attempts.",
          ],
          ordered: false,
        },
        {
          kind: "heading",
          level: 2,
          text: "Release advice",
        },
        {
          kind: "list",
          items: [
            "Entry gate. Testing starts when access works, two test businesses exist, the scope is agreed and the severity scale is accepted.",
            "Verdict. The summary says fix first if any Critical is open, or any High in booking, deposits or tenant separation. Otherwise it says go, with the listed known issues.",
            "Decision owner. The founder decides whether to launch. We advise; we do not certify the platform.",
          ],
          ordered: false,
        },
      ],
    },
    {
      n: 6,
      title: "Engineering decisions and trade-offs",
      blocks: [
        {
          kind: "table",
          rows: [
            ["Decision", "Why", "Trade-off"],
            [
              "Risk-based sessions with short checklists, not fully scripted cases",
              "No written specification existed, and session testing finds launch blockers sooner",
              "Less repeatable than scripts; a written list of what was not tested makes coverage explicit",
            ],
            [
              "Synthetic test businesses only",
              "Keeps real personal data out of the engagement",
              "Set-up time for test accounts and inboxes",
            ],
            [
              "Real devices for sign-off; emulation only for triage",
              "Install and Safari behaviour differ by platform",
              "Depends on device availability; cloud real devices fill gaps",
            ],
            [
              "One issue per record, bugs and UX notes on separate lists",
              "The developer can reproduce and fix without follow-up questions",
              "A little more writing time per issue",
            ],
            [
              "Non-intrusive security checks only",
              "Penetration testing was out of scope and the system was live",
              "Confirms obvious isolation faults only; gives no security assurance",
            ],
            [
              "Mollie test mode only",
              "No real money or card data is touched",
              "Live-mode behaviour is not covered; we advise one low-value live booking by the founder before launch",
            ],
          ],
        },
      ],
    },
    {
      n: 7,
      title: "Delivery plan",
      blocks: [
        {
          kind: "para",
          text: "The engagement runs in six phases with four gates. Hours are estimates, confirmed after a first look at the platform.",
        },
        {
          kind: "image",
          src: "/case-studies/delivery-plan.png",
          alt: "Delivery roadmap: 6 phases, 4 gates",
          width: 1200,
          height: 675,
        },
        {
          kind: "para",
          text: "Figure 2. Delivery roadmap: 6 phases, 4 gates",
        },
        {
          kind: "para",
          text: "Each diamond is a gate: work moves to the next phase only when its condition holds.",
        },
        {
          kind: "table",
          rows: [
            [
              "Phase",
              "Deliverables",
              "Exit gate",
              "Launch-critical (h)",
              "Full (h)",
            ],
            [
              "1. Kickoff and access",
              "Scoping answers, logins, scope agreed in writing",
              "Access works and scope is agreed",
              "1",
              "1 to 2",
            ],
            [
              "2. Test design and data",
              "Coverage matrix, test fixtures, agreed severity scale",
              "Two test businesses exist",
              "1.5 to 2",
              "2 to 3",
            ],
            [
              "3. Core journey pass",
              "TEST-001 to TEST-013; first defect batch",
              "Core charters executed; any Critical reported the same day",
              "7 to 9",
              "15 to 21",
            ],
            [
              "4. Cross-cutting pass",
              "TEST-014 to TEST-018",
              "Committed devices covered",
              "3.5 to 5",
              "9 to 13",
            ],
            [
              "5. Reporting and summary",
              "Final defect log, UX list, release summary, not-tested list",
              "Report quality check passed",
              "1.5 to 2.5",
              "3 to 4",
            ],
            [
              "6. Retest",
              "Retest report",
              "Every fix marked Verified or Reopened",
              "1.5 to 2.5",
              "2 to 3",
            ],
          ],
        },
        {
          kind: "heading",
          level: 2,
          text: "Two scope options",
        },
        {
          kind: "para",
          text: "The launch-critical option, an estimated 16 to 22 hours, covers the three priority areas end to end, sign-up and onboarding, the core emails, one plan tier in depth with spot checks on the others, and desktop Chrome, iPhone Safari and Android Chrome, with the retest included.",
        },
        {
          kind: "para",
          text: "The full coverage option, an estimated 32 to 46 hours, adds every rule and status, all payment methods offered, every plan tier, reminders, the complete device matrix and the installed PWA.",
        },
        {
          kind: "para",
          text: "Either way, the founder receives a written list of anything not covered, so nothing is skipped silently.",
        },
      ],
    },
    {
      n: 8,
      title: "What the founder receives",
      blocks: [
        {
          kind: "list",
          items: [
            "A defect log in the founder's own tracker or a shared sheet, one issue per record, with every field the brief asked for.",
            "A separate list of UX and improvement suggestions.",
            "A tenant-separation check sheet showing what was attempted and the result.",
            "An evidence pack of screenshots and recordings, named by defect ID.",
            "A one-page release summary with the fix-first or go verdict, traced to the logged issues.",
            "A list of what was not tested and why.",
            "A retest report covering every fix, plus a smoke re-run of the core journeys.",
          ],
          ordered: false,
        },
        {
          kind: "para",
          text: "Working rhythm. A progress note each testing day; any Critical defect reported privately the same working day; the retest started within two working days of the developer reporting fixes. All test data carries a TEST prefix so it can be purged at close, and the tester's access is removed when the work ends.",
        },
      ],
    },
    {
      n: 9,
      title: "Target outcomes",
      blocks: [
        {
          kind: "para",
          text: "Targets are set before testing and measured during the engagement.",
        },
        {
          kind: "table",
          rows: [
            ["Measure", "How it is calculated", "Target"],
            [
              "Coverage of the agreed scope",
              "In-scope requirements with at least one executed test, divided by in-scope requirements",
              "100%",
            ],
            [
              "Report completeness",
              "Reports with every mandatory field, divided by all reports",
              "100%",
            ],
            [
              "First-attempt reproducibility",
              "Defects the developer reproduces at the first attempt, divided by defects reported",
              "90% or more",
            ],
            [
              "Device coverage",
              "Committed device and browser combinations executed, divided by those committed",
              "100%",
            ],
            [
              "Fix verification",
              "Fixed defects verified at retest, divided by fixes retested",
              "Reported, not targeted: it measures the fixes",
            ],
          ],
        },
        {
          kind: "para",
          text: "We do not forecast a bug count. A clean result would show the tested journeys work; it would not prove the platform secure or scalable.",
        },
      ],
    },
    {
      n: 10,
      title: "Risks we plan for",
      blocks: [
        {
          kind: "table",
          rows: [
            ["Risk", "How we manage it"],
            [
              "Scope wider than the time available, so thin coverage is read as complete",
              "Two scope options and a written not-tested list",
            ],
            [
              "Testing on a live instance reaches real users",
              "TEST-prefixed businesses, test inboxes only, purge at close",
            ],
            [
              "No written expected behaviour, so bug versus intended is disputed",
              "A Question status for unclear items; plan limits and rules requested at kickoff",
            ],
            [
              "Test-mode payments differ from live set-up",
              "Limitation stated; one low-value live booking by the founder advised before launch",
            ],
            [
              "Reminders, trial end and renewals cannot be triggered in the test window",
              "Developer asked to shorten timers; otherwise marked Blocked and listed in the summary",
            ],
            [
              "A real cross-tenant exposure is found",
              "Related checks paused and the founder told privately the same working day",
            ],
            [
              "A clean report is read as security or performance assurance",
              "Exclusions stated plainly in the summary, with specialist tests recommended",
            ],
          ],
        },
      ],
    },
    {
      n: 11,
      title: "What this engagement does not cover",
      blocks: [
        {
          kind: "para",
          text: "Load and performance testing, penetration testing, accessibility conformance audits and legal or regulatory compliance reviews sit outside this scope, and live-mode payments are not exercised. The release summary says so plainly. Where they matter, we recommend them as follow-on work: an automated smoke suite for the booking and payment paths, an email sender-authentication review, an accessibility review, a load test and a specialist penetration test.",
        },
      ],
    },
    {
      n: 12,
      title: "About Clickmasters",
      blocks: [
        {
          kind: "para",
          text: "Clickmasters is a software house and digital agency with 13 years in business, serving clients across Pakistan, the GCC, the UK, Europe, the USA and Malaysia. Its software practice covers custom software and SaaS development, API integration, QA and DevOps.",
        },
        {
          kind: "para",
          text: "Next step. Preparing to onboard your first customers onto a booking, scheduling or subscription product? Contact Clickmasters through Clickmasterssoftwaredevelopmentcompany.com with a short description of your platform. We will reply with scoping questions and a written estimate for both scope options.",
        },
        {
          kind: "heading",
          level: 2,
          text: "Sources",
        },
        {
          kind: "para",
          text: "Checked on 5 October 2026.",
        },
        {
          kind: "list",
          items: [
            "Testing, Mollie documentation.",
            "Handling payment status, Mollie documentation.",
            "OWASP Top 10:2025, Introduction, OWASP.",
            "Making PWAs installable, MDN Web Docs.",
          ],
          ordered: false,
        },
      ],
    },
  ],
};

export default caseStudy;
